---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-{{ .Release.Namespace }}
  labels:
    app: {{ template "eventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{.Release.Service}}"
